# Generated by Django 3.2.8 on 2022-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_clients_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.CharField(default=123, max_length=15, verbose_name='telephone'),
            preserve_default=False,
        ),
    ]
